apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  containers:
  - name: {{ .Values.app.name }}
    image: {{ .Values.pod.image }}
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
